### 회원 가입

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "andy10@podo.com",
    "password": "12341qwre",
    "username": "andy434"
}

### 로그인

Post http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "abc@abc.com",
    "password" : "1234"
}

### 로그인 2 : LoginGuard
POST http://localhost:3000/auth/login2
content-type: application/json

{
    "email" : "andy10@podo.com",
    "password" : "12341qwre"
}

### Guard 테스트
GET http://localhost:3000/auth/test-guard


### 로그인 3 :  ❶ 세션을 사용하는 테스트 
POST http://localhost:3000/auth/login3
content-type: application/json

{
    "email" : "andy10@podo.com",
    "password" : "12341qwre"
}

### 로그인 3 :  ❷ 틀린 패스워드로 테스트 
POST http://localhost:3000/auth/login3
content-type: application/json

{
    "email" : "andy10@podo.com",
    "password" : "12341qwre"
}

### ❸ 인증이 성공 하는지 테스트
GET http://localhost:3000/auth/test-guard2