### 회원 가입

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "andy10@podo.com",
    "password": "12341qwre",
    "username": "andy434"
}

### 로그인

Post http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "abc@abc.com",
    "password" : "1234"
}